image: node:latest

default:
  before_script:
    - npm ci

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run ci:test
  artifacts:
    paths:
      - output.json
      - coverage/*
    expire_in: 1 week

deploy:
  script:
    - npm run-script deploy -- --stage=production
  artifacts:
    paths:
      - deploy.txt
    expire_in: 1 week
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v.*/
  environment: production

deploy_UAT:
  script:
    - branch=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | sed s:hotfix/::g | sed s:bugfix/::g | sed s:feature/::g  | sed s:/:-:g | cut -c1-7 )
    - npm run-script deploy -- --stage=$(echo $branch)
  only:
    - merge_requests
  artifacts:
    paths:
      - deploy.txt
    expire_in: 1 week

terminate:
  script:
    - branch=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | sed s:hotfix/::g | sed s:bugfix/::g | sed s:feature/::g  | sed s:/:-:g | cut -c1-7 )
    - npm run-script remove -- --stage=$(echo $branch)
  when: manual
  only:
    - merge_requests
  artifacts:
    paths:
      - remove.txt
    expire_in: 1 week
