image: node:latest

default:
  before_script:
    - npm ci

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run ci:test
  artifacts:
    paths:
      - output.json
      - coverage/*
    expire_in: 1 week
  allow_failure: false

deploy:
  script:
    - npm install serverless -g
    - serverless config credentials --stage=production --provider aws --key $(echo $AWS_ACCESS_KEY_ID) --secret $(echo $AWS_SECRET_ACCESS_KEY)
    - npm run-script deploy -- --stage=production  > deploy.txt
  artifacts:
    paths:
      - deploy.txt
    expire_in: 1 week
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v.*/
  environment: production

deploy_UAT:
  script:
    - npm install serverless -g
    - branch=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | sed s:hotfix/::g | sed s:bugfix/::g | sed s:feature/::g  | sed s:/:-:g | cut -c1-7 )
    - echo $branch
    - serverless config credentials --provider aws --key $(echo $AWS_ACCESS_KEY_ID) --secret $(echo $AWS_SECRET_ACCESS_KEY) --stage=$(echo $branch)
    - npm run-script deploy -- --stage=$(echo $branch)  > deploy.txt
    - info=$(npm run-script info -- --stage=$(echo $branch))
    - curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployed $(echo $BITBUCKET_BRANCH)\n$(echo $info | sed -e 's/.*endpoints:\(.*\)functions:.*/\1/g')"}' https://hooks.slack.com/services/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
  only:
    - merge_requests
  artifacts:
    paths:
      - deploy.txt
    expire_in: 1 week
  when: manual

terminate:
  script:
    - npm install serverless -g
    - branch=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | sed s:hotfix/::g | sed s:bugfix/::g | sed s:feature/::g  | sed s:/:-:g | cut -c1-7 )
    - serverless config credentials --stage=$(echo $branch) --provider aws --key $(echo $AWS_ACCESS_KEY_ID) --secret $(echo $AWS_SECRET_ACCESS_KEY)
    - npm run-script remove -- --stage=$(echo $branch)  > remove.txt
  when: manual
  only:
    - merge_requests
  artifacts:
    paths:
      - remove.txt
    expire_in: 1 week
