image: node:12.19.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm ci
          - output=$((npm run ci:test)2>&1)
          - pipe: atlassian/slack-notify:0.3.6
            variables:
              WEBHOOK_URL: $SLACK_WEBHOOK_URL
              MESSAGE: $(echo $output)
        artifacts:
          - ./coverage/*
          - ./output.json
  tags:
    v*:
      - step:
          caches:
            - node
          name: Release
          script:
            - npm ci
            - npm run-script deploy > ./deploy.txt
            - output = $(cat ./deploy.txt)
            - pipe: atlassian/slack-notify:0.3.6
              variables:
                WEBHOOK_URL: $SLACK_WEBHOOK_URL
                MESSAGE: $(echo $output | sed -e 's/.*endpoints:\(.*\)functions:.*/\1/')
          artifacts:
            - ./deploy.txt
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - branch=$(BITBUCKET_BRANCH////-)
            - npm ci
            - sls config credentials --stage $(branch:0:7) --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - npm run-script deploy -- --stage=$(branch:0:7)  > ./deploy.txt
            - output = $(cat ./deploy.txt)
            - pipe: atlassian/slack-notify:0.3.6
              variables:
                WEBHOOK_URL: $SLACK_WEBHOOK_URL
                MESSAGE: $(echo $output | sed -e 's/.*endpoints:\(.*\)functions:.*/\1/' )
          artifacts:
            - ./deploy.txt
definitions:
  caches:
    npm: $HOME/.npm
