image: node:12.19.0

pipelines:
  default:
    - step:
        script:
          - npm ci
          - npm run ci:test
        artifacts:
          - ./coverage/*
          - ./output.json
  tags:
    v*:
      - step:
          name: Build and release
          script:
            - npm ci
            - npm run-script deploy > ./deploy.txt
          artifacts:
            - ./deploy.txt
  pull-requests:
    '**':
      - step:
          script:
            - branch=$(BITBUCKET_BRANCH////-)
            - npm ci
            - serverless config credentials --stage $(branch:0:7) --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - npm run-script deploy -- --stage=$(branch:0:7)  > ./deploy.txt
          artifacts:
            - ./deploy.txt
definitions:
  caches:
    npm: $HOME/.npm
