service:
  name: producer-template

custom:
  # https://www.serverless.com/plugins/serverless-webpack
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules:
      forceExclude:
        - aws-sdk
        - aws-lambda
    excludeFiles: functions/__tests__/**/*.spec.ts # Provide a glob for files to ignore
    series: true # run Webpack in series, useful for large projects. Defaults to false.
    packager: 'npm' # Packager that will be used to package your external modules

package:
  individually: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    APIG_DEPLOYMENT_ID: ApiGatewayDeployment${sls:instanceId}
    VERSION: 0.0.1
functions:
  productTemplate_status:
    handler: functions/status/src/index.handler
    events:
      - http:
          method: get
          path: status
  productTemplate_version:
    handler: functions/version/src/index.handler
    events:
      - http:
          method: get
          path: version
