service:
  name: aws-nodejs-typescript

custom:
  webpack:
    webpackConfig: functions/webpack.config.js

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: functions/src/index.handler
    events:
      - http:
          method: get
          path: hello
