service:
  name: aws-nodejs-typescript

custom:
  webpack:
    includeModules: true
    excludeFiles: *.spec.ts

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: functions/src/index.handler
    events:
      - http:
          method: get
          path: hello
