service:
  name: aws-nodejs-typescript

custom:
  # https://www.serverless.com/plugins/serverless-webpack
  webpack:
    webpackConfig: './webpack.config.js' # Name of webpack configuration file
    includeModules:
      forceExclude:
        - aws-sdk
    excludeFiles: functions/test/**/*.spec.ts # Provide a glob for files to ignore
    series: true # run Webpack in series, useful for large projects. Defaults to false.
    packager: 'npm' # Packager that will be used to package your external modules

package:
    individually: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

functions:
  hello:
    handler: functions/src/index.handler
    events:
      - http:
          method: get
          path: hello
