name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests then deploy UAT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        id: test
        run: npm test
      - name: Notify test success
        if: ${{ success() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests performed successfully
          slack-optional-icon_emoji: ':soleil_avec_visage:'
      - name: Notify test failure
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests failed
          slack-optional-icon_emoji: ':gobelin_japonais:'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy UAT
        run: npm run-script deploy -- --stage=${REF////-}
        env:
          REF: ${{ github.event.pull_request.head.ref }}
      - name: Get UAT info
        run: echo ::set-env name=SLS_OUTPUT::$(npm run-script info -- --stage=${REF////-})
        env:
          REF: ${{ github.event.pull_request.head.ref }}
      - name: Notify UAT deployment completed successfully
        if: ${{ success() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Deployed successfully to ${{ github.event.pull_request.head.ref }} ${{ env.SLS_OUTPUT }}
          slack-optional-icon_emoji: ':soleil_avec_visage:'
      - name: Notify UAT deployment failure
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Failed to deploy to ${{ github.event.pull_request.head.ref }}
          slack-optional-icon_emoji: ':gobelin_japonais:'
