name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Deploy UAT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: identify
        run: |
          export GIT_REF="${{ github.event.pull_request.head.ref  }}"
          echo "::set-output name=git_ref::${GIT_REF////-}"
      - name: Deploy UAT
        run: npm run-script deploy -- --stage=${REF:0:7} > ./deploy.txt
        env:
          REF: ${{ steps.identify.outputs.git_ref }}
      - name: Get UAT info
        id: info
        run: |
          sls_output=$(npm run-script info -- --stage=${REF:0:7})
          echo "::set-output name=sls_output::$(echo $sls_output | sed -e 's/.*endpoints:\(.*\)functions:.*/\1/' | sed $'s/ GET/\\\<br/>&/g')"
        env:
          REF: ${{ steps.identify.outputs.git_ref }}
      - run: echo ${{steps.info.outputs.sls_output}}
      - name: Archive deployment artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deployment
          path: ./deploy.txt
      - name: Notify UAT deployment completed successfully
        if: ${{ success() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: |
            Deployed successfully to ${{ github.event.pull_request.head.ref }}
            ${{ steps.info.outputs.sls_output }}
          slack-optional-icon_emoji: ':soleil_avec_visage:'
      - name: Notify UAT deployment failure
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Failed to deploy to ${{ github.event.pull_request.head.ref }}
          slack-optional-icon_emoji: ':gobelin_japonais:'
