name: Push branch
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npx jest --ci
      - name: Archive tests artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: ./output.json
          retention-days: 5
      - name: Archive code coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
          retention-days: 5
      - name: Notify test success
        if: ${{ success() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests OK
          slack-optional-icon_emoji: ':soleil_avec_visage:'
      - name: Notify test failure
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests NOK
          slack-optional-icon_emoji: ':gobelin_japonais:'
