name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci --only=dev
      - name: Run tests
        id: test
        run: npm test
      - name: Send success message to Slack API
        if: ${{ success() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests performed successfully
          slack-optional-icon_emoji: ':soleil_avec_visage:'
      - name: Send failure message to Slack API
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: continue
          slack-text: Tests failed
          slack-optional-icon_emoji: ':gobelin_japonais:'
